/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author kshintaku
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        currVertRate = new javax.swing.JLabel();
        downButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        currYPos = new javax.swing.JLabel();
        vertLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        xLabel = new javax.swing.JLabel();
        horiLabel = new javax.swing.JLabel();
        currXPos = new javax.swing.JLabel();
        currHoriRate = new javax.swing.JLabel();
        upLeftButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        upRightButton = new javax.swing.JButton();
        downLeftButton = new javax.swing.JButton();
        downRightButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Telescope Positioning");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.darkGray);

        cancelButton.setText("Ø");
        cancelButton.setPreferredSize(new java.awt.Dimension(45, 45));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        currVertRate.setText("0");

        downButton.setText("↓");
        downButton.setPreferredSize(new java.awt.Dimension(45, 45));
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        leftButton.setText("←");
        leftButton.setPreferredSize(new java.awt.Dimension(45, 45));
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        rightButton.setText("→");
        rightButton.setPreferredSize(new java.awt.Dimension(45, 45));
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        currYPos.setText("0");

        vertLabel.setText("Current Vertical Rate:");

        yLabel.setText("Y-Position:");

        xLabel.setText("X-Position:");

        horiLabel.setText("Current Horizontal Rate:");

        currXPos.setText("0");

        currHoriRate.setText("0");

        upLeftButton.setText("↖");
        upLeftButton.setPreferredSize(new java.awt.Dimension(45, 45));
        upLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upLeftButtonActionPerformed(evt);
            }
        });

        upButton.setText("↑");
        upButton.setPreferredSize(new java.awt.Dimension(45, 45));
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        upRightButton.setText("↗");
        upRightButton.setPreferredSize(new java.awt.Dimension(45, 45));
        upRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upRightButtonActionPerformed(evt);
            }
        });

        downLeftButton.setText("↙");
        downLeftButton.setPreferredSize(new java.awt.Dimension(45, 45));
        downLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downLeftButtonActionPerformed(evt);
            }
        });

        downRightButton.setText("↘");
        downRightButton.setPreferredSize(new java.awt.Dimension(45, 45));
        downRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downRightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(horiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(currHoriRate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(downLeftButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(downRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(upRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vertLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currVertRate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currXPos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currYPos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vertLabel)
                    .addComponent(currVertRate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horiLabel)
                    .addComponent(currHoriRate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yLabel)
                    .addComponent(currYPos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xLabel)
                    .addComponent(currXPos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        currHoriRate.getAccessibleContext().setAccessibleName("currHoriRate");
        currHoriRate.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        currVertRate.setText("0");
        currHoriRate.setText("0");
        downButton.setEnabled(true);
        upButton.setEnabled(true);
        rightButton.setEnabled(true);
        leftButton.setEnabled(true);
        upLeftButton.setEnabled(true);
        upRightButton.setEnabled(true);
        downLeftButton.setEnabled(true);
        downRightButton.setEnabled(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        // Down button code to decrease vertical rate to max (-10)
        if (!swingTimer.isRunning()) {
            swingTimer.start();
        }
        int currVRate = Integer.parseInt(currVertRate.getText());
        int currHRate = Integer.parseInt(currHoriRate.getText());
        currVRate -= 1;
        currVertRate.setText(String.valueOf(currVRate));
        if (currVRate == -10) {
            downButton.setEnabled(false);
            downLeftButton.setEnabled(false);
            downRightButton.setEnabled(false);
        }
        if (currVRate < 10) {
            upButton.setEnabled(true);
            if (currHRate < 10) {
                upRightButton.setEnabled(true);
            }
            if (currHRate > -10) {
                upLeftButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_downButtonActionPerformed

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        // Left button code to decrease horizontal rate to max (-10)
        if (!swingTimer.isRunning()) {
            swingTimer.start();
        }
        int currVRate = Integer.parseInt(currVertRate.getText());
        int currHRate = Integer.parseInt(currHoriRate.getText());
        currHRate -= 1;
        currHoriRate.setText(String.valueOf(currHRate));
        if (currHRate == -10) {
            leftButton.setEnabled(false);
            upLeftButton.setEnabled(false);
            downLeftButton.setEnabled(false);
        }
        if (currHRate < 10) {
            rightButton.setEnabled(true);
            if (currVRate < 10) {
                upRightButton.setEnabled(true);
            }
            if (currVRate > -10) {
                downRightButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_leftButtonActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        // Right button code to increase horizontal rate to max (10)
        if (!swingTimer.isRunning()) {
            swingTimer.start();
        }
        int currHRate = Integer.parseInt(currHoriRate.getText());
        int currVRate = Integer.parseInt(currVertRate.getText());
        currHRate += 1;
        currHoriRate.setText(String.valueOf(currHRate));
        if (currHRate == 10) {
            rightButton.setEnabled(false);
            upRightButton.setEnabled(false);
            downRightButton.setEnabled(false);
        }
        if (currHRate > -10) {
            leftButton.setEnabled(true);
            if (currVRate < 10) {
                upLeftButton.setEnabled(true);
            }
            if (currVRate > -10) {
                downLeftButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_rightButtonActionPerformed

    private void upLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upLeftButtonActionPerformed
        // UP and LEFT button, disables if UP OR LEFT is maxed out
        if (!swingTimer.isRunning()) {
            swingTimer.start();
        }
        int currHRate = Integer.parseInt(currHoriRate.getText());
        int currVRate = Integer.parseInt(currVertRate.getText());
        currVRate += 1;
        currHRate -= 1;
        currHoriRate.setText(String.valueOf(currHRate));
        currVertRate.setText(String.valueOf(currVRate));
        if (currVRate == 10) {
            upButton.setEnabled(false);
            upLeftButton.setEnabled(false);
            upRightButton.setEnabled(false);
        }
        else {
            downButton.setEnabled(true);
            downRightButton.setEnabled(true);
            if (currHRate > -10) {
                downLeftButton.setEnabled(true);
            }
        }
        if (currHRate == -10) {
            leftButton.setEnabled(false);
            upLeftButton.setEnabled(false);
            downLeftButton.setEnabled(false);
        }
        else {
            rightButton.setEnabled(true);
            downRightButton.setEnabled(true);
            if (currVRate < 10) {
                upRightButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_upLeftButtonActionPerformed

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        // Up button code to increase vertical rate to max (10)
        if (!swingTimer.isRunning()) {
            swingTimer.start();
        }
        int currVRate = Integer.parseInt(currVertRate.getText());
        int currHRate = Integer.parseInt(currHoriRate.getText());
        currVRate += 1;
        currVertRate.setText(String.valueOf(currVRate));
        if (currVRate == 10) {
            upButton.setEnabled(false);
            upLeftButton.setEnabled(false);
            upRightButton.setEnabled(false);
        }
        if (currVRate > -10) {
            downButton.setEnabled(true);
            if (currHRate < 10) {
                downRightButton.setEnabled(true);
            }
            if (currHRate > -10) {
                downLeftButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_upButtonActionPerformed

    private void upRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upRightButtonActionPerformed
        // Up and Right button, disables is UP OR RIGHT is maxed
        if (!swingTimer.isRunning()) {
            swingTimer.start();
        }
        int currHRate = Integer.parseInt(currHoriRate.getText());
        int currVRate = Integer.parseInt(currVertRate.getText());
        currVRate += 1;
        currHRate += 1;
        currHoriRate.setText(String.valueOf(currHRate));
        currVertRate.setText(String.valueOf(currVRate));
        if (currVRate == 10) {
            upButton.setEnabled(false);
            upLeftButton.setEnabled(false);
            upRightButton.setEnabled(false);
        }
        else {
            downButton.setEnabled(true);
            downLeftButton.setEnabled(true);
            if (currHRate < 10) {
                downRightButton.setEnabled(true);
            }
        }
        if (currHRate == 10) {
            rightButton.setEnabled(false);
            upRightButton.setEnabled(false);
            downRightButton.setEnabled(false);
        }
        else {
            leftButton.setEnabled(true);
            downLeftButton.setEnabled(true);
            if (currVRate < 10) {
                upLeftButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_upRightButtonActionPerformed

    private void downLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downLeftButtonActionPerformed
        // DOWN and LEFT button, disables if DOWN OR LEFT is maxed out
        if (!swingTimer.isRunning()) {
            swingTimer.start();
        }
        int currHRate = Integer.parseInt(currHoriRate.getText());
        int currVRate = Integer.parseInt(currVertRate.getText());
        currVRate -= 1;
        currHRate -= 1;
        currHoriRate.setText(String.valueOf(currHRate));
        currVertRate.setText(String.valueOf(currVRate));
        if (currVRate == -10) {
            downButton.setEnabled(false);
            downLeftButton.setEnabled(false);
            downRightButton.setEnabled(false);
        }
        else {
            upButton.setEnabled(true);
            upRightButton.setEnabled(true);
            if (currHRate > -10) {
                downRightButton.setEnabled(true);
            }
        }
        if (currHRate == -10) {
            leftButton.setEnabled(false);
            downLeftButton.setEnabled(false);
            upLeftButton.setEnabled(false);
        }
        else {
            rightButton.setEnabled(true);
            upRightButton.setEnabled(true);
            if (currVRate > -10) {
                upLeftButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_downLeftButtonActionPerformed

    private void downRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downRightButtonActionPerformed
        // DOWN and RIGHT button, disables if DOWN OR RIGHT is maxed out
        if (!swingTimer.isRunning()) {
            swingTimer.start();
        }
        int currHRate = Integer.parseInt(currHoriRate.getText());
        int currVRate = Integer.parseInt(currVertRate.getText());
        currVRate -= 1;
        currHRate += 1;
        currHoriRate.setText(String.valueOf(currHRate));
        currVertRate.setText(String.valueOf(currVRate));
        if (currVRate == -10) {
            downButton.setEnabled(false);
            downLeftButton.setEnabled(false);
            downRightButton.setEnabled(false);
        }
        else {
            upButton.setEnabled(true);
            upLeftButton.setEnabled(true);
            if (currHRate < 10) {
                downLeftButton.setEnabled(true);
            }
        }
        if (currHRate == 10) {
            rightButton.setEnabled(false);
            upRightButton.setEnabled(false);
            downRightButton.setEnabled(false);
        }
        else {
            leftButton.setEnabled(true);
            upLeftButton.setEnabled(true);
            if (currVRate > -10) {
                upRightButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_downRightButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    private void setTimer() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currHoriRate;
    private javax.swing.JLabel currVertRate;
    private javax.swing.JLabel currXPos;
    private javax.swing.JLabel currYPos;
    private javax.swing.JButton downButton;
    private javax.swing.JButton downLeftButton;
    private javax.swing.JButton downRightButton;
    private javax.swing.JLabel horiLabel;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton upButton;
    private javax.swing.JButton upLeftButton;
    private javax.swing.JButton upRightButton;
    private javax.swing.JLabel vertLabel;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel yLabel;
    // End of variables declaration//GEN-END:variables
    
    // Timer running on 1 second to update current axis position based on horizontal
    // and vertical rates
    private javax.swing.Timer swingTimer = new Timer(1000, new ActionListener() {
        // Timer is started on main thread but ActionEvent is handled in separate thread
        @Override
        public void actionPerformed(ActionEvent e) {
            // Simple calculations to add rate to current position
            // TODO: Check against min or max values
            currYPos.setText(String.valueOf(Integer.parseInt(currYPos.getText()) + Integer.parseInt(currVertRate.getText())));
            currXPos.setText(String.valueOf(Integer.parseInt(currXPos.getText()) + Integer.parseInt(currHoriRate.getText())));
        }
    });
}
